describe('Sequoia landing page', () => {
  it('Check all the element in the page', () => {
   cy.viewport(1920,1080)
   cy.visit('https://www.sequoiaat.com/index.html')
   cy.title().should('eq','Sequoia Applied Technologies')
   cy.contains(`button`, `Embedded`).click()
   cy.url().should('eq', 'https://www.sequoiaat.com/embedded.html')
   cy.contains(`button`, `Mobile App`).click()
   cy.url().should('eq', 'https://www.sequoiaat.com/mobile-app.html')
   cy.contains(`button`, `Cloud`).click()
   cy.url().should('eq', 'https://www.sequoiaat.com/cloud-services.html')
   cy.contains(`button`, `Testing`).click()
   cy.url().should('eq', 'https://www.sequoiaat.com/testing.html')
   cy.contains(`button`, `AI & ML`).click()
   cy.url().should('eq', 'https://www.sequoiaat.com/AI-ML.html')
   cy.get('#btn-menu').should('be.visible').click();
   cy.contains(`a`, `About Us`).click()
   cy.url().should('eq', 'https://www.sequoiaat.com/about-us.html')
   cy.get('.sequoia-text-circle').click()
   cy.url().should('eq', 'https://www.sequoiaat.com/about-us.html#content')
   cy.contains(`div`, `Management Team`).click()
   cy.get('#managers-list').click()
   cy.url().should('eq', 'undefined')
  })
})